#!/bin/sh

SOURCES="/usr/local/etc/pot"
DEST="./system"
RID=$(head -c100 /dev/urandom | strings -n1 | tr -d '[:space:]' | head -c15)

# 0. reset hard
git reset --hard

# 1. fetch the lastest from main
git fetch --progress --prune --recurse-submodules=no origin
git checkout main
git merge --ff --ff-only refs/remotes/origin/main
git checkout main

# 3. create new branch "system-copy-<RANDOM_ID>"
git branch --no-track docs refs/heads/main
git checkout system-copy-$RID

# 4. add all files to the newly created branch && commit
git add --force -- .
git commit -m "system-copy-$RID: $(date -u)"

# 5. push to git && create a merge request

for SOURCE in $SOURCES
do
  DERIVED_FILE_NAME="$(dirname $DEST$SOURCE)"
  echo "DERIVED: $DERIVED_FILE_NAME"


  if [ -d $SOURCE ]
  then
    mkdir -p "$DERIVED_FILE_NAME"
    cp -R $SOURCE $DERIVED_FILE_NAME
  elif [ -f $SOURCE ]
  then
    echo "[F] $SOURCE"
  else
    echo "$SOURCE is not valid"
    exit 1
  fi
done
