#!/bin/sh

# referece: https://tldp.org/LDP/abs/html/string-manipulation.html

# git fetch --progress --prune --recurse-submodules=no origin
# git pull

SOURCES=[ "/usr/local/etc/pot/" ]

for source in $SOURCES
do
  echo "$source"
done