#!/bin/sh

# referece: https://tldp.org/LDP/abs/html/string-manipulation.html

git fetch --progress --prune --recurse-submodules=no origin
git pull

SYSTEM_PREFIX="./system"

copy_file_to_system () {
  ORIGINAL_FILE_NAME=$1
  DERIVED_FILE_NAME="${ORIGINAL_FILE_NAME#$SYSTEM_PREFIX}"

  cp -f $ORIGINAL_FILE_NAME $DERIVED_FILE_NAME
}

find ./system -type f | while read file_name; do copy_file_to_system "$file_name"; done